### ISSUE TITLE
Disable unneeded features of dependencies

### ISSUE THREAD

**Issue by johanhelsing** [frewsxcv/bevy-web-resizer#1]
This looks like a neat solution to something that a lot of people will probably need :)

It would be cool if it didn't pull in more features from bevy and web-sys than absolutely necessary. For instance as it is now, I don't think it's possible to use it with bevy-kira-audio, as that's incompatible with bevy's audio feature.

**Comment by frewsxcv** [comment]
Sounds good to me! Do you know what the minimal set of features needed to build this crate would be?

**Comment by johanhelsing** [comment]
I would just try setting `default-features = false` for bevy and web-sys and then enable features until it compiles.

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/bevy-web-resizer/commit/70b20e642fa749cc1858b164672806d4e07e40f5

**Comment by johanhelsing** [comment]
What about web-sys?

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/bevy-web-resizer/commit/5a0aa8d22fafc0c92fefd8b935f340b7808a7e65

**Comment by johanhelsing** [comment]
Thanks! :)
