### ISSUE TITLE
Rust Analyzer complains, but code still works

### ISSUE THREAD

**Issue by miketwenty1** [frewsxcv/bevy-web-resizer#3]
I'm unsure if I'm doing something wrong, but Rust Analyzer doesn't like this and says it won't work, but it does seem to work just fine.

at the top of mian.rs
`use bevy_web_resizer;`

In Cargo.toml
under dependencies:
`bevy-web-resizer = "2.0.0"`

![Screen Shot 2022-07-17 at 2 10 11 PM](https://user-images.githubusercontent.com/7761473/179419174-f098740d-0c11-4c80-b2b4-539cb2a8b779.png)

**Comment by frewsxcv** [comment]
See the readme for the project. You need to add a `cfg` platform flag

**Comment by frewsxcv** [comment]
@miketwenty1 Did that resolve your issue?

**Comment by miketwenty1** [comment]
Adding 
`#[cfg(target_arch = "wasm32")]`
above my main function grey's out my main function and I get other errors about not having a main function.

I'm creating the bevy app in my main function and also adding:
`.add_plugin(bevy_web_resizer::Plugin)`
as one of the plugins.

Not sure what the proper way to get rust analyzer to be happy.. it still works with and without the cfg line.

**Comment by frewsxcv** [comment]
I recommend reading more about `cfg` from the documentation: https://doc.rust-lang.org/reference/conditional-compilation.html

By adding `#[cfg(target_arch = "wasm32")]` above `main`, that means there will be no `main` function on non-wasm32 architectures.

**Comment by miketwenty1** [comment]
makes sense.. just not sure how to get rust analyzer to be accepting of me only caring about the wasm target.

**Comment by frewsxcv** [comment]
There might be a rust analyzer setting to change the target architecture

**Comment by miketwenty1** [comment]
perhaps.. I'm guessing there's a much easier way to implement this similar to how you suggest in the README though.

```rust
fn main() {
    let height = 900.0;
    let app = App::new()
        .insert_resource(ClearColor(CLEAR))
        .insert_resource(WindowDescriptor {
            width: height * RESOLUTION,
            height: height,
            title: "Wonder".to_string(),
            present_mode: PresentMode::Fifo,
            resizable: false,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .add_plugin(PlayerPlugin)
        .add_plugin(BlockPlugin)
        .add_startup_system(setup_system)
        .add_startup_system_to_stage(StartupStage::PreStartup, spritesheet_system)
        .add_plugin(DebugPlugin)
        .run();

    #[cfg(target_arch = "wasm32")]
    {
        app.add_plugin(bevy_web_resizer::Plugin);
    }
}
```

How would I modify this code to add in this plugin correctly?

**Comment by frewsxcv** [comment]
```
    let app = App::new()
        .insert_resource(ClearColor(CLEAR))
        .insert_resource(WindowDescriptor {
            width: height * RESOLUTION,
            height: height,
            title: "Wonder".to_string(),
            present_mode: PresentMode::Fifo,
            resizable: false,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .add_plugin(PlayerPlugin)
        .add_plugin(BlockPlugin)
        .add_startup_system(setup_system)
        .add_startup_system_to_stage(StartupStage::PreStartup, spritesheet_system)
        .add_plugin(DebugPlugin);

    #[cfg(target_arch = "wasm32")]
    {
        app.add_plugin(bevy_web_resizer::Plugin);
    }

    
    app.run();
```

**Comment by miketwenty1** [comment]
![Screen Shot 2022-07-17 at 9 13 31 PM](https://user-images.githubusercontent.com/7761473/179432900-035782cf-59ed-4213-8cda-d45474524944.png)

Doesn't seem like it's happy with running app.run() afterwards.

**Comment by frewsxcv** [comment]
Separate the `app::new()` onto its own line

https://github.com/frewsxcv/rgis/blob/main/rgis/src/lib.rs#L21-L60

**Comment by miketwenty1** [comment]
thank you so much!
